language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services: mongodb
script:
  - yarn build &
  - yarn test
  - yarn coverage
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn run coveralls
